yarnPath: .yarn/releases/yarn-4.9.4.cjs

nodeLinker: node-modules

npmScopes:
  bob-park:
    npmRegistryServer: "https://npm.pkg.github.com"

npmRegistries:
  //npm.pkg.github.com:
    npmAuthToken: "${GITHUB_NPM_AUTH_TOKEN}"
