import type { Metadata } from 'next';

import { cookies } from 'next/headers';

import { HydrationBoundary, QueryClient, dehydrate } from '@tanstack/react-query';

import RQProvider from '@/shared/components/queries/RQProvider';
import ToastProvider from '@/shared/components/toast/ToastProvider';

import './globals.css';

const { WEB_SERVICE_HOST } = process.env;

const COOKIE_NAME_THEME = 'theme';
const COOKIE_NAME_TOKEN = 'auth-token';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();

  const theme = (cookieStore.get(COOKIE_NAME_THEME)?.value ?? 'light') as Theme;

  const queryClient = new QueryClient();

  const res = await fetch(`${WEB_SERVICE_HOST}/users/me`, {
    method: 'get',
    headers: {
      Cookie: `${COOKIE_NAME_TOKEN}=${cookieStore.get(COOKIE_NAME_TOKEN)?.value || ''}`,
    },
  });

  let user;

  if (res.ok) {
    user = (await res.json()) as User;
  }
  const dehydratedState = dehydrate(queryClient);

  return (
    <html lang="ko" data-theme={theme}>
      <body className="relative size-full">
        <RQProvider>
          <HydrationBoundary state={dehydratedState}>
            <ToastProvider limit={5} timeout={5}>
              {children}
            </ToastProvider>
          </HydrationBoundary>
        </RQProvider>
      </body>
    </html>
  );
}
